post:
  tags:
    - 강아지
  summary: 강아지 등록
  description: 새로운 강아지 정보를 등록한다.
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
              description: 강아지 이름
            breed:
              type: string
              description: 견종
            gender:
              type: string
              description: 강아지 성별
              enum:
                - MALE
                - FEMALE
            isNeutered:
              type: boolean
              description: 중성화 여부
            birth:
              type: string
              description: 강아지 생일
            profilePhotoUrl:
              type: string
              description: 강아지 사진 URL
              example: https://path/to/profile-photo
          required:
            - name
            - breed
            - gender
            - isNeutered
            - birth
            - profilePhotoUrl
  responses:
    "201":
      description: 강아지가 정상적으로 등록된 경우
      content:
        text/plain:
          schema:
            type: boolean
            example: true
    "401":
      description: Authorization header가 없거나 유효한 access token이 아닌 경우
    "404":
      description: 회원을 찾을 수 없는 경우
