name: Frontend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"

env:
  IMAGE: dangdang-front
  REPO: 180993267331.dkr.ecr.ap-northeast-2.amazonaws.com
  TAG: ${GITHUB_SHA::7}
  EC2_SSH_USER: ubuntu

jobs:
  build:
    name: ECR Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.2.0
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: setEnv
        run: |
          echo "IMAGE=dangdang-front" >> $GITHUB_ENV
          echo "REPO=180993267331.dkr.ecr.ap-northeast-2.amazonaws.com" >> $GITHUB_ENV
          echo "hash=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "EC2_SSH_USER=ubuntu" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker build
        run: |
          docker build --platform linux/amd64 -t ${{ env.IMAGE }} --target prod .
      - name: ECR push
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ env.REPO }}
          docker tag ${{ env.IMAGE }} ${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
          docker push ${{ env.REPO }}/${{ env.IMAGE}}:${{ env.TAG }}
  deploy:
    needs: build
    runs-on: [ self-hosted, label-front ]
    steps:
      - name: Deploy to Amazon EC2
        run : |
          docker ps -q --filter "name=${{ env.IMAGE }}" | grep -q . && docker stop ${{ env.IMAGE }} && docker image prune -f
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ env.REPO }}
          docker pull ${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
          docker run -d --name ${{ env.IMAGE }} --restart always --rm -p 3000:3000 ${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
